language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - pypy
env:
  - FLASK_VERSION=0.8
  - FLASK_VERSION=0.9
  - FLASK_VERSION=0.10.1
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - pip install -r testapp/requirements.txt
  - pip install -I Flask==$FLASK_VERSION
  - pip install -e .
script:
  - PYTHONPATH=testapp/ nosetests -w testapp/
matrix:
  allow_failures:
    - pypy
  exclude:
    - python: 3.3
      env: FLASK_VERSION==0.8
    - python: 3.3
      env: FLASK_VERSION==0.9
